---
- hosts: all
  become: yes
  vars:
    # Define variables for NICE DCV and Parsec versions to easily update them
    nice_dcv_url: "https://d1uj6qtbmh3dt5.cloudfront.net/2023.1/Servers/nice-dcv-2023.1-16388-ubuntu2204-x86_64.tgz"
    parsec_url: "https://builds.parsec.app/package/parsec-linux.deb"
    ansible_user: root # Specify the user Ansible will connect as

  tasks:
    - name: Update apt cache and install initial packages
      apt:
        name:
          - mdadm
          - ubuntu-cinnamon-desktop
        state: present
        update_cache: yes

    - name: Configure RAID 10 Array
      community.general.raid:
        level: 10
        devices:
          - /dev/sdb
          - /dev/sdc
          - /dev/sdd
          - /dev/sde
        raid_device: /dev/md0
        state: present

    - name: Create a filesystem on the RAID device
      filesystem:
        fstype: ext4
        dev: /dev/md0

    - name: Create mount point for RAID array
      file:
        path: /mnt/raid10
        state: directory
        mode: '0755'

    - name: Mount the RAID device
      mount:
        path: /mnt/raid10
        src: /dev/md0
        fstype: ext4
        state: mounted

    - name: Install NVIDIA drivers using ubuntu-drivers
      command: ubuntu-drivers autoinstall
      register: nvidia_install_result
      changed_when: "'already installed' not in nvidia_install_result.stdout"

    - name: Reboot the server to load NVIDIA drivers
      reboot:
        msg: "Rebooting to apply NVIDIA driver installation"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
      when: nvidia_install_result.changed

    - name: Verify NVIDIA driver installation
      command: nvidia-smi
      changed_when: false
      register: nvidia_smi_output

    - name: Display NVIDIA driver status
      debug:
        var: nvidia_smi_output.stdout_lines

    - name: Download and Install NICE DCV
      script: files/setup_dcv.sh "{{ nice_dcv_url }}"
      args:
        creates: /usr/bin/dcv

    - name: Download and Install Parsec
      script: files/setup_parsec.sh "{{ parsec_url }}"
      args:
        creates: /usr/bin/parsec

    - name: Run Parsec login script
      script: files/parsec_login.sh
      register: parsec_login_result
      changed_when: "'Login successful' in parsec_login_result.stdout"
      failed_when: "'Login failed' in parsec_login_result.stdout"

    - name: Enable Parsec service to start on boot
      systemd:
        name: parsecd
        enabled: yes
        state: started

    - name: Final message
      debug:
        msg: "Server setup is complete. You can now connect via Parsec or NICE DCV."
